import {useLocation} from 'react-router-dom'

// Custom Hook to extract path name from Object generated by useLocation()
const usePathname = () =>{
    const location = useLocation();
    return location.pathname;
    
}

export default usePathname